INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai', 2023, 2023, 'Annual', 'success', 'Al cierre de el cierre anual de 2023, tu gestión sobre tu posición global de solvencia evidencia una postura disciplinada y coherente, generando la holgura operativa necesaria para planear crecimientos futuros sin comprometer la estabilidad actual de tu estructura fiscal.', 'El balance de el cierre anual de 2023 expone una contracción nociva en tu posición global de solvencia que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Después de analizar el cierre anual de 2023, te exijo como medida urgente centralizar tus decisiones en sanear tu posición global de solvencia, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_1Q', 2023, 2023, '1Q', 'warning', 'Concluido el análisis de el 1Q de 2023, la fortaleza demostrada sobre tu posición global de solvencia refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Cerrando el 1Q de 2023, el deterioro observado en tu posición global de solvencia encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Con base en los resultados de el 1Q de 2023, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu posición global de solvencia, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_2Q', 2023, 2023, '2Q', 'info', 'Concluido el análisis de el 2Q de 2023, la fortaleza demostrada sobre tu posición global de solvencia refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Los datos de el 2Q de 2023 revelan fisuras estructurales preocupantes en tu posición global de solvencia, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'La acción prioritaria tras revisar el 2Q de 2023 es focalizar toda tu energía directiva en depurar tu posición global de solvencia; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_3Q', 2023, 2023, '3Q', 'danger', 'Al cierre de el 3Q de 2023, tu gestión sobre tu posición global de solvencia evidencia una postura disciplinada y coherente, generando la holgura operativa necesaria para planear crecimientos futuros sin comprometer la estabilidad actual de tu estructura fiscal.', 'Al revisar el 3Q de 2023, detectamos una debilidad crítica que está erosionando tu posición global de solvencia; esta situación activa alertas ejecutivas que no puedes ignorar, pues continuar en este rumbo compromete seriamente tu capacidad de sostenerse, operar y crecer.', 'La acción prioritaria tras revisar el 3Q de 2023 es focalizar toda tu energía directiva en depurar tu posición global de solvencia; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_4Q', 2023, 2023, '4Q', 'success', 'Revisando los registros de el 4Q de 2023, celebro tu habilidad para blindar tu posición global de solvencia, confirmando que las medidas implementadas han funcionado correctamente y que tu firma avanza con la autonomía directiva que toda organización exitosa debería proteger.', 'Analizando el 4Q de 2023, emerge un estancamiento silencioso en tu posición global de solvencia que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'Con base en los resultados de el 4Q de 2023, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu posición global de solvencia, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai', 2024, 2024, 'Annual', 'warning', 'Concluido el análisis de el cierre anual de 2024, la fortaleza demostrada sobre tu posición global de solvencia refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Cerrando el cierre anual de 2024, el deterioro observado en tu posición global de solvencia encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Con base en los resultados de el cierre anual de 2024, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu posición global de solvencia, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_1Q', 2024, 2024, '1Q', 'info', 'Revisando los registros de el 1Q de 2024, celebro tu habilidad para blindar tu posición global de solvencia, confirmando que las medidas implementadas han funcionado correctamente y que tu firma avanza con la autonomía directiva que toda organización exitosa debería proteger.', 'Los datos de el 1Q de 2024 revelan fisuras estructurales preocupantes en tu posición global de solvencia, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Con base en los resultados de el 1Q de 2024, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu posición global de solvencia, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_2Q', 2024, 2024, '2Q', 'danger', 'Al revisar tu balance de el 2Q de 2024, destaco que mantuviste un control firme sobre tu posición global de solvencia, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Analizando el 2Q de 2024, emerge un estancamiento silencioso en tu posición global de solvencia que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'Después de analizar el 2Q de 2024, te exijo como medida urgente centralizar tus decisiones en sanear tu posición global de solvencia, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_3Q', 2024, 2024, '3Q', 'success', 'Al revisar tu balance de el 3Q de 2024, destaco que mantuviste un control firme sobre tu posición global de solvencia, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'El balance de el 3Q de 2024 expone una contracción nociva en tu posición global de solvencia que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Para revertir el impacto negativo evidenciado en el 3Q de 2024, debes intervenir de inmediato sobre tu posición global de solvencia, suspendiendo gastos prescindibles, exigiendo cobros anticipados a clientes y reorientando tu músculo operativo hacia fortalecer tu posición fiscal sostenible.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_4Q', 2024, 2024, '4Q', 'warning', 'Revisando los registros de el 4Q de 2024, celebro tu habilidad para blindar tu posición global de solvencia, confirmando que las medidas implementadas han funcionado correctamente y que tu firma avanza con la autonomía directiva que toda organización exitosa debería proteger.', 'Los datos de el 4Q de 2024 revelan fisuras estructurales preocupantes en tu posición global de solvencia, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Tras el diagnóstico de el 4Q de 2024, debes actuar decididamente sobre tu posición global de solvencia; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai', 2025, 2025, 'Annual', 'info', 'Finalizado el corte de el cierre anual de 2025, es gratificante comprobar que protegiste eficazmente tu posición global de solvencia, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'Cerrando el cierre anual de 2025, el deterioro observado en tu posición global de solvencia encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Después de analizar el cierre anual de 2025, te exijo como medida urgente centralizar tus decisiones en sanear tu posición global de solvencia, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_1Q', 2025, 2025, '1Q', 'danger', 'Concluido el análisis de el 1Q de 2025, la fortaleza demostrada sobre tu posición global de solvencia refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Los datos de el 1Q de 2025 revelan fisuras estructurales preocupantes en tu posición global de solvencia, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Con base en los resultados de el 1Q de 2025, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu posición global de solvencia, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_2Q', 2025, 2025, '2Q', 'success', 'Al cierre de el 2Q de 2025, tu gestión sobre tu posición global de solvencia evidencia una postura disciplinada y coherente, generando la holgura operativa necesaria para planear crecimientos futuros sin comprometer la estabilidad actual de tu estructura fiscal.', 'Al revisar el 2Q de 2025, detectamos una debilidad crítica que está erosionando tu posición global de solvencia; esta situación activa alertas ejecutivas que no puedes ignorar, pues continuar en este rumbo compromete seriamente tu capacidad de sostenerse, operar y crecer.', 'La acción prioritaria tras revisar el 2Q de 2025 es focalizar toda tu energía directiva en depurar tu posición global de solvencia; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_3Q', 2025, 2025, '3Q', 'warning', 'Concluido el análisis de el 3Q de 2025, la fortaleza demostrada sobre tu posición global de solvencia refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Cerrando el 3Q de 2025, el deterioro observado en tu posición global de solvencia encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Tras el diagnóstico de el 3Q de 2025, debes actuar decididamente sobre tu posición global de solvencia; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'insight-solvencia-ai_4Q', 2025, 2025, '4Q', 'info', 'Al revisar tu balance de el 4Q de 2025, destaco que mantuviste un control firme sobre tu posición global de solvencia, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'El balance de el 4Q de 2025 expone una contracción nociva en tu posición global de solvencia que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Después de analizar el 4Q de 2025, te exijo como medida urgente centralizar tus decisiones en sanear tu posición global de solvencia, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque A v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;
