INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'cargos_fijos', 2023, 2023, 'Annual', 'danger', 'Al revisar tu balance de el cierre de 2023, destaco que mantuviste un control firme sobre tu cobertura de cargos fijos, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Los datos de el cierre de 2023 revelan fisuras estructurales preocupantes en tu cobertura de cargos fijos, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Tras el diagnóstico de el cierre de 2023, debes actuar decididamente sobre tu cobertura de cargos fijos; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'intereses', 2023, 2023, 'Annual', 'success', 'Al cierre de el cierre de 2023, tu gestión sobre tu cobertura de intereses financieros evidencia una postura disciplinada y coherente, generando la holgura operativa necesaria para planear crecimientos futuros sin comprometer la estabilidad actual de tu estructura fiscal.', 'Analizando el cierre de 2023, emerge un estancamiento silencioso en tu cobertura de intereses financieros que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'La acción prioritaria tras revisar el cierre de 2023 es focalizar toda tu energía directiva en depurar tu cobertura de intereses financieros; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'servicio_deuda', 2023, 2023, 'Annual', 'warning', 'Finalizado el corte de el cierre de 2023, es gratificante comprobar que protegiste eficazmente tu servicio de deuda total, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'El balance de el cierre de 2023 expone una contracción nociva en tu servicio de deuda total que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Tras el diagnóstico de el cierre de 2023, debes actuar decididamente sobre tu servicio de deuda total; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'deuda_ebitda', 2023, 2023, 'Annual', 'info', 'Revisando los registros de el cierre de 2023, celebro tu habilidad para blindar tu relación entre deuda y generación operativa, confirmando que las medidas implementadas han funcionado correctamente y que tu firma avanza con la autonomía directiva que toda organización exitosa debería proteger.', 'Analizando el cierre de 2023, emerge un estancamiento silencioso en tu relación entre deuda y generación operativa que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'Tras el diagnóstico de el cierre de 2023, debes actuar decididamente sobre tu relación entre deuda y generación operativa; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'endeudamiento_total', 2023, 2023, 'Annual', 'danger', 'Al revisar tu balance de el cierre de 2023, destaco que mantuviste un control firme sobre tu nivel global de endeudamiento, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Cerrando el cierre de 2023, el deterioro observado en tu nivel global de endeudamiento encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Después de analizar el cierre de 2023, te exijo como medida urgente centralizar tus decisiones en sanear tu nivel global de endeudamiento, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'solvencia_patrimonial', 2023, 2023, 'Annual', 'success', 'Al revisar tu balance de el cierre de 2023, destaco que mantuviste un control firme sobre tu solvencia patrimonial, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'El balance de el cierre de 2023 expone una contracción nociva en tu solvencia patrimonial que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Con base en los resultados de el cierre de 2023, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu solvencia patrimonial, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'cargos_fijos', 2024, 2024, 'Annual', 'warning', 'Finalizado el corte de el cierre de 2024, es gratificante comprobar que protegiste eficazmente tu cobertura de cargos fijos, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'Analizando el cierre de 2024, emerge un estancamiento silencioso en tu cobertura de cargos fijos que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'Después de analizar el cierre de 2024, te exijo como medida urgente centralizar tus decisiones en sanear tu cobertura de cargos fijos, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'intereses', 2024, 2024, 'Annual', 'info', 'Finalizado el corte de el cierre de 2024, es gratificante comprobar que protegiste eficazmente tu cobertura de intereses financieros, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'Cerrando el cierre de 2024, el deterioro observado en tu cobertura de intereses financieros encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Para revertir el impacto negativo evidenciado en el cierre de 2024, debes intervenir de inmediato sobre tu cobertura de intereses financieros, suspendiendo gastos prescindibles, exigiendo cobros anticipados a clientes y reorientando tu músculo operativo hacia fortalecer tu posición fiscal sostenible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'servicio_deuda', 2024, 2024, 'Annual', 'danger', 'Al revisar tu balance de el cierre de 2024, destaco que mantuviste un control firme sobre tu servicio de deuda total, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Los datos de el cierre de 2024 revelan fisuras estructurales preocupantes en tu servicio de deuda total, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Después de analizar el cierre de 2024, te exijo como medida urgente centralizar tus decisiones en sanear tu servicio de deuda total, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'deuda_ebitda', 2024, 2024, 'Annual', 'success', 'Al revisar tu balance de el cierre de 2024, destaco que mantuviste un control firme sobre tu relación entre deuda y generación operativa, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Cerrando el cierre de 2024, el deterioro observado en tu relación entre deuda y generación operativa encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Después de analizar el cierre de 2024, te exijo como medida urgente centralizar tus decisiones en sanear tu relación entre deuda y generación operativa, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'endeudamiento_total', 2024, 2024, 'Annual', 'warning', 'Finalizado el corte de el cierre de 2024, es gratificante comprobar que protegiste eficazmente tu nivel global de endeudamiento, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'Al revisar el cierre de 2024, detectamos una debilidad crítica que está erosionando tu nivel global de endeudamiento; esta situación activa alertas ejecutivas que no puedes ignorar, pues continuar en este rumbo compromete seriamente tu capacidad de sostenerse, operar y crecer.', 'La acción prioritaria tras revisar el cierre de 2024 es focalizar toda tu energía directiva en depurar tu nivel global de endeudamiento; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'solvencia_patrimonial', 2024, 2024, 'Annual', 'info', 'Al revisar tu balance de el cierre de 2024, destaco que mantuviste un control firme sobre tu solvencia patrimonial, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Analizando el cierre de 2024, emerge un estancamiento silencioso en tu solvencia patrimonial que compromete gravemente tu resiliencia; sin una intervención oportuna y decidida, este patrón podría derivar en una espiral de pérdida de control rentable progresiva.', 'Para revertir el impacto negativo evidenciado en el cierre de 2024, debes intervenir de inmediato sobre tu solvencia patrimonial, suspendiendo gastos prescindibles, exigiendo cobros anticipados a clientes y reorientando tu músculo operativo hacia fortalecer tu posición fiscal sostenible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'cargos_fijos', 2025, 2025, 'Annual', 'danger', 'Revisando los registros de el cierre de 2025, celebro tu habilidad para blindar tu cobertura de cargos fijos, confirmando que las medidas implementadas han funcionado correctamente y que tu firma avanza con la autonomía directiva que toda organización exitosa debería proteger.', 'Cerrando el cierre de 2025, el deterioro observado en tu cobertura de cargos fijos encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Con base en los resultados de el cierre de 2025, la recomendación es clara y directa: prioriza sin excepciones el fortalecimiento de tu cobertura de cargos fijos, paralizando toda expansión hasta recuperar el equilibrio mínimo que garantice tu independencia operacional plena.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'intereses', 2025, 2025, 'Annual', 'success', 'Finalizado el corte de el cierre de 2025, es gratificante comprobar que protegiste eficazmente tu cobertura de intereses financieros, demostrando que tu equipo directivo actuó con precisión y que la estrategia financiera actual está generando los resultados positivos que buscabas.', 'Cerrando el cierre de 2025, el deterioro observado en tu cobertura de intereses financieros encendió alertas directivas urgentes que exigen atención inmediata; ignorar esta señal equivale a permitir que tus reservas operativas se consuman sin generar el retorno esperado necesario.', 'Después de analizar el cierre de 2025, te exijo como medida urgente centralizar tus decisiones en sanear tu cobertura de intereses financieros, cortando convenios ineficientes, exigiendo anticipos reales de clientes y blindando tu liquidez antes de asumir cualquier nuevo compromiso operativo.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'servicio_deuda', 2025, 2025, 'Annual', 'warning', 'Concluido el análisis de el cierre de 2025, la fortaleza demostrada sobre tu servicio de deuda total refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'El balance de el cierre de 2025 expone una contracción nociva en tu servicio de deuda total que está desviando recursos críticos hacia cubrir déficits perfectamente evitables, empujando tu operación hacia una posición estructuralmente frágil con poco margen real de reacción.', 'Para revertir el impacto negativo evidenciado en el cierre de 2025, debes intervenir de inmediato sobre tu servicio de deuda total, suspendiendo gastos prescindibles, exigiendo cobros anticipados a clientes y reorientando tu músculo operativo hacia fortalecer tu posición fiscal sostenible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'deuda_ebitda', 2025, 2025, 'Annual', 'info', 'Concluido el análisis de el cierre de 2025, la fortaleza demostrada sobre tu relación entre deuda y generación operativa refleja una conducción gerencial sólida, sirviendo como plataforma confiable para escalar operaciones rentablemente y negociar condiciones favorables con tus clientes y socios estratégicos.', 'Al revisar el cierre de 2025, detectamos una debilidad crítica que está erosionando tu relación entre deuda y generación operativa; esta situación activa alertas ejecutivas que no puedes ignorar, pues continuar en este rumbo compromete seriamente tu capacidad de sostenerse, operar y crecer.', 'La acción prioritaria tras revisar el cierre de 2025 es focalizar toda tu energía directiva en depurar tu relación entre deuda y generación operativa; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'endeudamiento_total', 2025, 2025, 'Annual', 'danger', 'Al cierre de el cierre de 2025, tu gestión sobre tu nivel global de endeudamiento evidencia una postura disciplinada y coherente, generando la holgura operativa necesaria para planear crecimientos futuros sin comprometer la estabilidad actual de tu estructura fiscal.', 'Los datos de el cierre de 2025 revelan fisuras estructurales preocupantes en tu nivel global de endeudamiento, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'La acción prioritaria tras revisar el cierre de 2025 es focalizar toda tu energía directiva en depurar tu nivel global de endeudamiento; esto implica negociar condiciones más favorables con proveedores, eliminar compromisos superfluos y asegurar que cada peso genere retorno medible.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;

INSERT INTO insights (empresa_id, indicador_key, periodo_ano, year, period_key, tipo, analisis_positivo, analisis_negativo, recomendacion, metodologia, generado_por, created_at)
VALUES (3099, 'solvencia_patrimonial', 2025, 2025, 'Annual', 'success', 'Al revisar tu balance de el cierre de 2025, destaco que mantuviste un control firme sobre tu solvencia patrimonial, ratificando que tus decisiones gerenciales fueron las adecuadas y que tu firma opera con la solidez esperada para este nivel de exigencia.', 'Los datos de el cierre de 2025 revelan fisuras estructurales preocupantes en tu solvencia patrimonial, lo que indica que tu operación está absorbiendo presiones que reducen tu margen de maniobra y ponen en riesgo directo tu autonomía financiera directiva.', 'Tras el diagnóstico de el cierre de 2025, debes actuar decididamente sobre tu solvencia patrimonial; este momento crítico exige eliminar costos inoperantes, cobrar cuentas vencidas urgentemente y comprometer a tu equipo en metas concretas de recuperación financiera mensurable.', 'Bloque B v4.6c', 'antigravity', NOW())
ON CONFLICT (empresa_id, indicador_key, periodo_ano, period_key) DO UPDATE SET
tipo=EXCLUDED.tipo, analisis_positivo=EXCLUDED.analisis_positivo, analisis_negativo=EXCLUDED.analisis_negativo, recomendacion=EXCLUDED.recomendacion, metodologia=EXCLUDED.metodologia, generado_por=EXCLUDED.generado_por;
